[[ExtensibleChoiceParameterplugin-ChangeLog]]
== Change Log

:sectanchors:

[[ExtensibleChoiceParameterplugin-Version1.8.0]]
=== 1.8.0

Release date: Jul 31, 2021

* Expose choices to remote access API even without `+Item.BUILD+` permission for some choice providers. (https://issues.jenkins.io/browse/JENKINS-66145[JENKINS-66145])
** Following choice providers:
*** Textarea Choice Parameter
** For plugin developers: Overriding `+ChoiceListProviders#requiresBuildPermission+` to return `+false+` allows exposing choices to remote access API without `+Item.BUILD+` permission. It should be allowed only when choices can be calculated only from the job configuration for security reasons.

[[ExtensibleChoiceParameterplugin-Version1.7.0]]
=== 1.7.0

Release date: Nov 7, 2020

* Expose choices to remote access API (https://issues.jenkins-ci.org/browse/JENKINS-63786[JENKINS-63786])
** You can retrieve choice values in JENKINS_URI/job/JOBNAME/api/json and so on. See https://www.jenkins.io/doc/book/using/remote-access-api/ for more details aboud remote access API.
** An empty list will be returned if you don't have `+Item.BUILD+` permission for that job.
* Move documentation to GitHub (https://github.com/jenkinsci/extensible-choice-parameter-plugin/pull/45[#45])

[[ExtensibleChoiceParameterplugin-Version1.6.0]]
=== 1.6.0

Release date: May 20, 2018

* Add an option to switch the behavior of input value when the input is
editable
(https://issues.jenkins-ci.org/browse/JENKINS-22316[JENKINS-22316],
https://issues.jenkins-ci.org/browse/JENKINS-50315[JENKINS-50315])
** You can select "Display all choices" (the behavior same to Extensible
Choice Paramter <= 1.4.2) or "Display only matching choices" (the
behavior same to Extensible Choice Paramter 1.5.0).
** "Display all choices" is the default behavior.

[[ExtensibleChoiceParameterplugin-Version1.5.0]]
=== 1.5.0

Release date: Mar 17, 2018

* Filter options by input when the input is editable
(https://issues.jenkins-ci.org/browse/JENKINS-22316[JENKINS-22316])
* Save as more simple configurations
(https://issues.jenkins-ci.org/browse/JENKINS-49210[JENKINS-49210])

[[ExtensibleChoiceParameterplugin-Version1.4.2]]
=== 1.4.2

Release date: Jan 27, 2018

* Compatible with Jenkins >= 2.102
(https://issues.jenkins-ci.org/browse/JENKINS-49017[JENKINS-49017]) +
** See https://jenkins.io/blog/2018/01/13/jep-200/[JEP-200] for more
details
* Fix typo
(https://github.com/jenkinsci/extensible-choice-parameter-plugin/pull/32[PR
#32])

[[ExtensibleChoiceParameterplugin-Version1.4.1]]
=== 1.4.1

Release date: Aug 27, 2017

* FIXED: HTML in description is always escaped
(https://issues.jenkins-ci.org/browse/JENKINS-42903[JENKINS-42903])
* Fix typo
(https://github.com/jenkinsci/extensible-choice-parameter-plugin/pull/29[PR
#29])

[[ExtensibleChoiceParameterplugin-Version1.4.0]]
=== 1.4.0

Release date: Apr 10, 2017

* SECURITY FIX:
https://jenkins.io/security/advisory/2017-04-10/#extensible-choice-parameter-plugin[Jenkins
Security Advisory 2017-04-10#Extensible Choice Parameter Plugin]
** Groovy scripts run with https://plugins.jenkins.io/script-security/[Script Security Plugin]
** Existing scripts are configured to run in the script sandbox.
** You might require approve some methods for the sandbox, or configure
scripts run without the sandbox and approve scripts.
* Targets Jenkins >= 1.580.1.
* The pre-defined variable 'jenkins' is no longer provided.
** You can get Jenkins instance with `+jenkins.model.Jenkins.instance+`
instead. Require appropriate approving.

[[ExtensibleChoiceParameterplugin-Version1.3.4]]
=== 1.3.4

Release date: Jan 28, 2017

* Use the top most value if the specified default parameter isn't
contained in the choice list.
** Note: Builds fail if you passed a value not contained in the choice
list explicitly (e.g. via Parameterized trigger plugin).

[[ExtensibleChoiceParameterplugin-Version1.3.3]]
=== 1.3.3

Release date: Oct 22, 2016

* FIXED: "Top Most Value" is replaced with an empty value when saved
before the job configuration page is completed to be load
(https://issues.jenkins-ci.org/browse/JENKINS-37147[JENKINS-37147])

[[ExtensibleChoiceParameterplugin-Version1.3.2]]
=== 1.3.2

Release date: Aug 23, 2015

* Fixed UnsupportedOperationException when Empty Choice is configured
for File Choice Parameter
(https://issues.jenkins-ci.org/browse/JENKINS-29934[JENKINS-29934])
* Improved the help of Exclude Pattern of File Choice Parameter.

[[ExtensibleChoiceParameterplugin-Version1.3.1]]
=== 1.3.1

Release date: Jun 20, 2015

* Fixed NPE with "List Files Now" in configuration pages
(https://issues.jenkins-ci.org/browse/JENKINS-28841[JENKINS-28841],
regression in 1.3.0)

[[ExtensibleChoiceParameterplugin-Version1.3.0]]
=== 1.3.0

Release date: May 05, 2015

* Now you can disable specific providers in system configuration page
(https://issues.jenkins-ci.org/browse/JENKINS-27375[JENKINS-27375]).
** See
https://github.com/jenkinsci/extensible-choice-parameter-plugin/blob/master/README.adoc#ExtensibleChoiceParameterplugin-Disablingproviders[#Disabling
providers] for details.
* Validates parameter names by checking they can be handled by Jenkins
core
(https://issues.jenkins-ci.org/browse/JENKINS-22222[JENKINS-22222]).
* Fixed "Error: No stapler-class is specified" when saving project
configuation with Jenkins
1.610(https://issues.jenkins-ci.org/browse/JENKINS-28046[JENKINS-28046]).
** Dot letters are allowed for variable names with Jenkins > 1.526.
* Added an empty choice option to FilenameChoiceListProvider
(https://issues.jenkins-ci.org/browse/JENKINS-22318[JENKINS-22318]).
* Also accepts $class introduced in Jenkins 1.588
(https://issues.jenkins-ci.org/browse/JENKINS-25403[JENKINS-25403]).

[[ExtensibleChoiceParameterplugin-Version1.2.2]]
=== 1.2.2

Release date: Dec 08, 2013

* Added feature to use `+project+` in System Groovy Script.
https://issues.jenkins-ci.org/browse/JENKINS-17875[JENKINS-17875]
* Added feature to reverse file lists.

[[ExtensibleChoiceParameterplugin-Version1.2.1]]
=== 1.2.1

Release date: Jun 22, 2013

* Added documents for System Groovy Script Choice Parameter.
* Added "Run the Script Now" Button for System Groovy Script Choice
Parameter.

[[ExtensibleChoiceParameterplugin-Version1.2.0]]
=== 1.2.0

Release date: May 03, 2013

* Added new providers
** System Groovy Script Choice Parameter: runs a System Groovy script to
determine the list of choices
** File Choice Parameter: lists files in a directory.
* Added checkbox "Add Edited Value" to Textarea Choice Parameter and
Global Choice Parameter. By checking this, edited values used in builds
are automatically added to choices.

[[ExtensibleChoiceParameterplugin-Version1.1.0]]
=== 1.1.0

Release date: Feb 06, 2013

* Now you can select the default choice in each job.
* Fixed the misspell.

[[ExtensibleChoiceParameterplugin-Version1.0.0]]
=== 1.0.0

Release date: Jan 07, 2013

* Initial release.
